/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src;

import java.awt.BorderLayout;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author a2320606
 */
public class ListarEventosPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListarEventosPanel
     */
    private JTable table;
    public ListarEventosPanel() {
        initComponents();
        setLayout(new BorderLayout(0, 0));
        table = new JTable(getDataColumns(), getNameColumns());
        JScrollPane scroll = new JScrollPane(table);
        add(scroll, BorderLayout.CENTER);

    }
    
    public void addNewRow(Object[] valores){
        ((DefaultTableModel)table.getModel()).addRow(valores);
    }

    private Vector<Vector<Object>> getDataColumns() {
        AgendaIO io = new AgendaIO();
        Vector<Vector<Object>> dataColumns = null;
        try {
            dataColumns = io.getEventos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"ERRO", ex.getMessage(),JOptionPane.ERROR_MESSAGE);
        }
        return dataColumns;
    }


    private Vector<String> getNameColumns(){
    Vector<String> nameColumns = new Vector<>();
    nameColumns.add("Data");
    nameColumns.add("Descrição");
    nameColumns.add("Periodicidade");
    nameColumns.add("E-mail");
    nameColumns.add("Alarme");
    return nameColumns;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
